$(function(){
  $(".qa-box-first").click(function(){
    $("#close-text-first").slideToggle();
    $(".right-arrow-first").toggleClass("add");
  });
  $(".qa-box-second").click(function(){
    $("#close-text-second").slideToggle();
    $(".right-arrow-second").toggleClass("add");
  });
  $(".qa-box-third").click(function(){
    $("#close-text-third").slideToggle();
    $(".right-arrow-third").toggleClass("add");
  });
  $(".qa-box-four").click(function(){
    $("#close-text-four").slideToggle();
    $(".right-arrow-four").toggleClass("add");
  });
  $(".qa-box-five").click(function(){
    $("#close-text-five").slideToggle();
    $(".right-arrow-five").toggleClass("add");
  });
  $(".qa-box-six").click(function(){
    $("#close-text-six").slideToggle();
    $(".right-arrow-six").toggleClass("add");
  });
  $(".qa-box-seven").click(function(){
    $("#close-text-seven").slideToggle();
    $(".right-arrow-seven").toggleClass("add");
  });
  $(".qa-box-eight").click(function(){
    $("#close-text-eight").slideToggle();
    $(".right-arrow-eight").toggleClass("add");
  });
  $(".qa-box-nine").click(function(){
    $("#close-text-nine").slideToggle();
    $(".right-arrow-nine").toggleClass("add");
  });
  $(".qa-box-ten").click(function(){
    $("#close-text-ten").slideToggle();
    $(".right-arrow-ten").toggleClass("add");
  });
  $(".qa-box-eleven").click(function(){
    $("#close-text-eleven").slideToggle();
    $(".right-arrow-eleven").toggleClass("add");
  });
  $(".qa-box-twelve").click(function(){
    $("#close-text-twelve").slideToggle();
    $(".right-arrow-twelve").toggleClass("add");
  });
  $(".qa-box-thirteen").click(function(){
    $("#close-text-thirteen").slideToggle();
    $(".right-arrow-thirteen").toggleClass("add");
  });
  $(".qa-box-fourteen").click(function(){
    $("#close-text-fourteen").slideToggle();
    $(".right-arrow-fourteen").toggleClass("add");
  });
  $(".qa-box-fifteen").click(function(){
    $("#close-text-fifteen").slideToggle();
    $(".right-arrow-fifteen").toggleClass("add");
  });
});
